# permissions for end users to view namespaceannotates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceannotate-viewer-role
rules:
- apiGroups:
  - devops.example.io
  resources:
  - namespaceannotates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.example.io
  resources:
  - namespaceannotates/status
  verbs:
  - get
