# permissions for end users to edit namespaceannotates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceannotate-editor-role
rules:
- apiGroups:
  - devops.example.io
  resources:
  - namespaceannotates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.example.io
  resources:
  - namespaceannotates/status
  verbs:
  - get
