---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devops.example.io
  resources:
  - namespaceannotates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.example.io
  resources:
  - namespaceannotates/finalizers
  verbs:
  - update
- apiGroups:
  - devops.example.io
  resources:
  - namespaceannotates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespace
  verbs:
  - get
  - list
  - patch
  - update
  - watch